### ISSUE TITLE
Rename `Predicate` to `Comparator` and `VersionReq` to `Range`

### ISSUE THREAD

**Issue by KodrAus** [steveklabnik/semver-parser#21]
In the [npm `semver` package](https://www.npmjs.com/package/semver#ranges), `Predicate`s are called `Comparator`s, and `VersionReq`s are called `Range`s. It might be worth making the naming here consistent with what they're doing so anybody getting started with `semver` and `semver_parser` in Rust can feel more familiar.

I think this one needs some more discussion to decide whether we want to go ahead with renaming things.

**Comment by est31** [comment]
`Range` from the npm package supports disjoint sets (`1.2.7 || >=1.2.9 <2.0.0`), while `VersionReq` from this package only supports intervals (`>=1.2.9 <2.0.0` and also `^1.2.3`).

The analogon to `VersionReq` from this crate would be `Comparator` from the npm package. Both are always (possibly unbounded) intervals. I don't think there should be any renaming at all though. People will always be confused :).

Even if `Predicate` got extended to support what `Comparator` supports and `VersionReq` got extended to support `Range`, I still wouldn't rename them because the term "Range" indicates an interval which it is not. The npm name is misleading :), if anything then the npm name should be changed.

**Comment by KodrAus** [comment]
Thanks! I think those are reasonable arguments against renaming things @est31. The goal of renaming the public items is simply to be consistent with the npm package, whether or not its own names actually make sense, so that the crate might be more familiar to more users.

Since appreciating your point requires familiarity with how the types work already, I don't think the npm names would make it harder to get started with it.

I agree with the idea that _if in doubt, don't change it_ though. So I'll have a hunt around at other semver libs in other languages and see if they follow a similar naming convention. If every library is different then it's probably not worth doing this.

**Comment by opilar** [comment]
Golang library (https://github.com/blang/semver) have the same `Range` notion as disjoint sets and internal notion of [comparator](https://github.com/blang/semver/blob/e3f131b368b4eb2a86c2e777374148c6396d4913/range.go#L32).

**Comment by steveklabnik** [comment]
This crate is no longer being used or maintained: https://github.com/steveklabnik/semver-parser/commit/dc6c1077899da46e89242041dda54ca36c170982
