### ISSUE TITLE
Using regex brings in too many dependencies for use in a build script

### ISSUE THREAD

**Issue by kamalmarhubi** [steveklabnik/semver-parser#7]
In https://github.com/Kimundi/rustc-version-rs/pull/5 I tried to have a non-panicking version of rustc-version. This required catching up with semver. Now that it pulls in regex, it has become a little too big to use in a build script if we update rustc-version to latest semver / semver-parser.

Would a hand-rolled parser be an option here? I saw that the motivation of the move to regex was that nom code was difficult to work with. A hand-rolled parser may or may not be an improvement, but it would drop the transitive dependencies to none.

**Comment by steveklabnik** [comment]
I actually created this crate in order to remove my the old hand-rolled parser. :smile: 

So I can see two or three paths forward here:
1. Port this back to a hand-rolled parser.
2. Update semver to be able to handle different, optional backends.
3. Update this crate to handle different, optional backends.

What do you think?

For some background:
1. I am terrified and terrible at parsers and love regexes, so that's part of my motivation here.
2. I expect many libraries will already have a regex dep, so I figured that it wasn't a big deal.
3. I also recognize that might not be true in every case and want to support it.

**Comment by kamalmarhubi** [comment]
> I expect many libraries will already have a regex dep, so I figured that it wasn't a big deal.

Debatable! Certainly not most build scripts. :-)

> I am terrified and terrible at parsers and love regexes, so that's part of my motivation here.

Yeah, I get that! Teasing it apart a bit more: is it more about modification being harder, or about being sure of correctness?

**Comment by kamalmarhubi** [comment]
Also for a bit of extra clarity: by "hand-rolled" I meant not-nom—just funtions. Something that would result in semver-parser having zero dependencies.

**Comment by steveklabnik** [comment]
Yes. I think zero deps is a good thing.

It's just a mental block for me; I've always been really bad at parsers. The old hand rolled one was also ANCIENT rust; it was made before regex was, even. So it's possible that a newer one would be easier to understand.

**Comment by steveklabnik** [comment]
fixed by https://github.com/steveklabnik/semver-parser/pull/12
